osx_image: xcode7.1
language: objective-c
script:
- set -o pipefail && xcodebuild -workspace WordPress-iOS-Shared.xcworkspace -scheme WordPressShared -sdk iphonesimulator build test ONLY_ACTIVE_ARCH=NO | xcpretty -c
